name: practice-sql-mysql

services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql-local
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: practice_db
      MYSQL_USER: practice_user
      MYSQL_PASSWORD: practice_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    networks:
      - mysql_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  

volumes:
  mysql_data:
    driver: local

networks:
  mysql_network:
    driver: bridge
    name: practice-sql-network
